### ISSUE TITLE
Bài tập tuần 1 (8/10/2020-15/10/2020)

### ISSUE THREAD

**Issue by ITHelpself** [ITHelpself/nhomlaptrinh#15]
![image](https://user-images.githubusercontent.com/34569793/95465399-4a8de880-09a5-11eb-8bca-e65f43e3fd90.png)

**Comment by ITHelpself** [comment]
![image](https://user-images.githubusercontent.com/34569793/95547816-faa73400-0a2d-11eb-8712-9ea88bbe9c05.png)
![image](https://user-images.githubusercontent.com/34569793/95547833-01ce4200-0a2e-11eb-9551-ac35f0932c5e.png)

**Comment by gbcrabber** [comment]
```pascal
 program cau1;
 uses crt;
 var a: integer;
 `Begin
    clrscr;
    Writeln('nhap so a: );
    Readln(a);
    If a mod 2 = 0 then
    Writeln('a la so chan');
    Else writeln('a la so le');
    Readln;
 End.
```
Em làm câu 1 đúng không mọi người?

**Comment by ITHelpself** [comment]
tư duy thì ổn nè e @gbcrabber

**Comment by ITHelpself** [comment]
lâu rồi a không viết pascal nên a không nhớ e viết đúng hay sai về mặt ngôn ngữ :')

**Comment by caoank61** [comment]
> ```pascal
> program cau1;
>  uses crt;
>  var a: integer;
>  `Begin
>     clrscr;
>     Writeln('nhap so a: );
>     Readln(a);
>     If a mod 2 = 0 then
>     Writeln('a la so chan');
>     Else writeln('a la so le')
>     Readln;
>  End.
> ```
> 
> Em làm câu 1 đúng không mọi người?

Bài này nên để real vì nó k nói rõ là âm hay dương nữa, gặp ông này khó tính sẽ bẻ ngay chỗ này

**Comment by ITHelpself** [comment]
còn c e test thử lại nhé :))

**Comment by ITHelpself** [comment]
ok

**Comment by ITHelpself** [comment]
hihi

**Comment by ITHelpself** [comment]
ok

**Comment by ITHelpself** [comment]
tìm chẵn lẻ: https://www.youtube.com/watch?v=GfH5o6RUz24&feature=youtu.be

**Comment by ITHelpself** [comment]
```C++
#include<stdio.h>
int main(){
	// khai bao bien
	int a;// dung a de kiem tra xem a co phai so chan hay khong
	printf("nhap a:");
	scanf("%d",&a);
	if(a%2==0){
		printf("%d la so chan", a);
		}
	else{
		printf("%d la so le", a);
	}
	return 0;	
}
```

**Comment by ITHelpself** [comment]
```C
#include<stdio.h>
int main(){
	double a = 3,b=4;
	double tong = a+b;
	double hieu = a-b;
	double tich = a*b;
	double thuong = a/b;
	printf("tong = %f, hieu = %f, tich = %f, thuong = %f ", tong, hieu, tich, thuong);
	return 0;	
}
```

**Comment by gbcrabber** [comment]
Bài 2:
```C
#include<stdio.h>

int main(){
	int a, b;
	float x;
	printf("ax+b=0\n");
	printf("\n nhap a: "); scanf("%d", &a);
	printf("\n nhap b: "); scanf("%d", &b);
	x=-b/a;
	if (a==o){
	   printf("%d la nghiem cua phuong trinh nay", b);
	}
	else{
	   printf("%f la nghiem cua phuong trinh nay", x);
	}
	return 0;
}
```
Anh xem giúp em xem câu này em làm đúng chưa nha. Cảm ơn anh.

**Comment by ITHelpself** [comment]
ok e @gbcrabber

**Comment by ITHelpself** [comment]
@gbcrabber 
![image](https://user-images.githubusercontent.com/34569793/95558424-698d8880-0a40-11eb-9c8b-44c904a35704.png)

**Comment by ITHelpself** [comment]
sau dấu ; là đưa xuống dòng khác
```C
printf("\n nhap a: "); scanf("%d", &a);
printf("\n nhap b: "); scanf("%d", &b);
```
-->
```C
printf("\n nhap a: ");
 scanf("%d", &a);
printf("\n nhap b: "); 
scanf("%d", &b);
```

**Comment by ITHelpself** [comment]
```C
if (a==o){
	   printf("%d la nghiem cua phuong trinh nay", b);
	}
```
```C a==0 ``` nhé, không phải ``` a==o ```

**Comment by ITHelpself** [comment]
```C
x=-b/a;
if (a==0){
	   printf("%d la nghiem cua phuong trinh nay", b);
	}
else{
	   printf("%f la nghiem cua phuong trinh nay", x);
	}
```
**```C x=-b/a; ```** làm trước rồi mới xét **```a```** à em? nếu **``` a=0 ```** thì tính **`x`** sao được?
--->
```C
if (a==0){
	   printf("%d la nghiem cua phuong trinh nay", b);
	}
else{
           x=-b/a;
	   printf("%f la nghiem cua phuong trinh nay", x);
	}
```
```

**Comment by ITHelpself** [comment]
```C
int a, b;
float x;
```
```C
 x=-b/a;
```
int/int =int. 3/4 = 0.75 nhưng mà int/int nên kết quả bằng 0. Mất đi phần thập phân
--->
```C
 x=-(float)b/a;
```

**Comment by gbcrabber** [comment]
> ```c
> if (a == o) {
> 	    printf ( " % d la nghiem cua phuong trinh nay " , b);
> 	}
> ```
> 
> `C a==0 ` nhé, not `a==o`

Uầy, chữ o và số 0 gần nhau.
Em đánh máy trong cơn đói. =))

**Comment by ITHelpself** [comment]
> > ```c
> > if (a == o) {
> > 	    printf ( " % d la nghiem cua phuong trinh nay " , b);
> > 	}
> > ```
> > 
> > 
> > `C a==0 ` nhé, not `a==o`
> 
> Uầy, chữ o và số 0 gần nhau.
> Em đánh máy trong cơn đói. =))

kkk e. anh cũng đói.

**Comment by gbcrabber** [comment]
![20201011_094313.jpg](https://user-images.githubusercontent.com/72547543/95669062-4da3f700-0ba6-11eb-9038-87e693376eab.jpg)![20201011_094338.jpg](https://user-images.githubusercontent.com/72547543/95669064-55639b80-0ba6-11eb-8b9b-ea90d1c6b4a6.jpg)

**Comment by ITHelpself** [comment]
![image](https://user-images.githubusercontent.com/34569793/95669107-079b6300-0ba7-11eb-8079-2bec10a6bf72.png)

**Comment by ITHelpself** [comment]
không viết thế này
``` C
if (a==0){
	if(b==0){
		if(c==0){
			}
		}
	}
```
-->
```C
if(a==0 && b==0 &&c==0){
}
```

**Comment by ITHelpself** [comment]
theo phương pháp `Po-Shen Loh`
```C
#include<stdio.h>
#include<math.h>
int main(){
	// khai báo
	float a,b,c,x1,x2;
	// nhâp
	printf("nhap he so cua phuong trinh:");
	scanf("%f%f%f",&a,&b,&c);
	// tính toan
	if(a==0){
		printf("phuong trinh khong phai phuong trinh bac 2");
	}
	else{
		// chuyen ve dang pon sel loh
		float temp = a;
		a = a/temp;
		b = b/temp;
		c = c/temp;
		if(pow(b,2)/4-c <0){
			printf("phuong trinh vo nghiem");
		}
		else if(pow(b,2)/4-c == 0){
			x1 = -b/2;
			printf("phuong trinh co 1 nghiem duy nhat: x= %.2f",x1);
		}
		else{
			x1 = -b/2 - pow(b,2)/4-c;
			x2 = -b/2 + pow(b,2)/4-c;
			printf("phuong trinh co 2 nghiem phan biet: x1= %.2f, x2 = %.2f",x1,x2);
		}
	}
	return 0;
}
```

**Comment by ITHelpself** [comment]
```C
#include<stdio.h>
int main(){
	float a1,b1,c1,a2,b2,c2,x,y;
	// nhap gia tri
	printf("nhap vao he so cua phuong trinh 1:");
	scanf("%f%f%f",&a1,&b1,&c1);
	printf("nhap vao he so cua phuong trinh 2:");
	scanf("%f%f%f",&a2,&b2,&c2);
	// kiem tra nghiem
	if((a1*b2==b1*a2)&&(a1*c2==c1*a2)){
		printf("phuong trinh vo so nghiem");	
	}
	else if((a1*b2==b1*a2)&&(a1*c2!=c1*a2)){
		printf("phuong trinh vo nghiem");
	}
	else{
		y = (c2*a1 - a2*c1)/(a1*b2-a2*b1);
		x = (c1 - b1*y)/a1;
		printf("x =%.2f, y= %.2f",x,y);
	}
	return 0;
}
```

**Comment by ITHelpself** [comment]
![image](https://user-images.githubusercontent.com/34569793/95697561-5c071700-0c69-11eb-9d52-9763d397c351.png)

**Comment by ITHelpself** [comment]
![image](https://user-images.githubusercontent.com/34569793/95884409-43504b80-0da6-11eb-826c-927009508bd1.png)

**Comment by ITHelpself** [comment]
![image](https://user-images.githubusercontent.com/34569793/95884464-58c57580-0da6-11eb-860d-6f11179dc557.png)

**Comment by gbcrabber** [comment]
Bài 4-Cách 2
```
#include<stdio.h>

int main(){
	float a1, b1, c1, a2, b2, c2, D, Dx, Dy, x, y;
	printf("Nhap cac he so: ");
	scanf("%f%f%f%f%f%f", &a1, &b1, &c1, &a2, &b2, &c2);
	D=a1*b2-a2*b1;
	Dx=c1*b2-c2*b1;
	Dy=a1*c2-a2*c1;
	if (D==0) {
		if ((Dx==0) && (Dy==0)) 
			printf("He phuong trinh co vo so nghiem!"); 
		else
		    printf("He phuong trinh vo nghiem!");}
    else {
	    x=Dx/D;
	    y=Dy/D;
	    printf("He phuong trinh co mot cap nghiem duy nhat (x, y) = (%f, %f)", x, y);
    } 
	return 0;
}
```
