### ISSUE TITLE
Thắc mắc về câu lệnh printf, scanf

### ISSUE THREAD

**Issue by gbcrabber** [ITHelpself/nhomlaptrinh#22]
Ý nghĩa của printf và scanf là gì?
Có giống write/writeln và read/readln của Pascal không?

**Comment by ITHelpself** [comment]
https://viettuts.vn/lap-trinh-c/printf-va-scanf-trong-c

**Comment by ITHelpself** [comment]
giống e nhé

**Comment by gbcrabber** [comment]
À. Có nghĩa là printf() in dư liệu vào console. Scanf() là lấy từ console làm đầu vào?
Cũng giống như em đặt một quả cam lên bàn (printf) cho mẹ, mẹ cầm quả cam lên (scanf) làm mấy múi ăn đỡ tăng xông.
Em nói vậy đúng không?

**Comment by ITHelpself** [comment]
print là in ra. scanf là nhập vào

**Comment by ITHelpself** [comment]
in ra cái màn hình đen đen là printf, nhập vào màn hình đen đen là scanf

**Comment by ITHelpself** [comment]
màn hình đen trong lập trình gọi là console

**Comment by gbcrabber** [comment]
Em chưa hiểu cho lắm.
Thường em sẽ lấy ví dụ minh họa nhằm thông não. Càng thực tế, sinh động em càng hiểu.
Em lấy ví dụ quả cam khi nãy có sát với thực tế chưa ạ?

**Comment by ITHelpself** [comment]
trí liên tưởng a không tốt nên anh không hiểu ví dụ quả cam
